//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportaExcelSql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_IMP_IMPORTADATOS
    {
        public int PK_IMP_IMPORTADATOS_ID { get; set; }
        public string TB_IMP_IMPORTADATOS_RutFacilitador { get; set; }
        public string TB_IMP_IMPORTADATOS_NombreFacilitador { get; set; }
        public string TB_IMP_IMPORTADATOS_FechaIngreso { get; set; }
        public string TB_IMP_IMPORTADATOS_FechaAsignación { get; set; }
        public string TB_IMP_IMPORTADATOS_FechaEvaluación { get; set; }
        public string TB_IMP_IMPORTADATOS_NombreEvaluador { get; set; }
        public string TB_IMP_IMPORTADATOS_SectorModulo { get; set; }
        public string TB_IMP_IMPORTADATOS_SubSectorModulo { get; set; }
        public string TB_IMP_IMPORTADATOS_TipoModulo { get; set; }
        public string TB_IMP_IMPORTADATOS_PlanFormativo { get; set; }
        public string TB_IMP_IMPORTADATOS_NombreModulo { get; set; }
        public string TB_IMP_IMPORTADATOS_Estado { get; set; }
        public string TB_IMP_IMPORTADATOS_Correo { get; set; }
        public string TB_IMP_IMPORTADATOS_Teléfono { get; set; }
        public string TB_IMP_IMPORTADATOS_Comuna { get; set; }
        public string TB_IMP_IMPORTADATOS_Región { get; set; }
        public string TB_IMP_IMPORTADATOS_FechaEnvio { get; set; }
    }
}
